/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/vendors` | `/vendors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/shop` | `/shop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/wishlist` | `/wishlist`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/vendors` | `/vendors`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/categories` | `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/shop` | `/shop`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/wishlist` | `/wishlist`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/vendors${`?${string}` | `#${string}` | ''}` | `/vendors${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/categories${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/shop${`?${string}` | `#${string}` | ''}` | `/shop${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/wishlist${`?${string}` | `#${string}` | ''}` | `/wishlist${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/vendors` | `/vendors`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/shop` | `/shop`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/wishlist` | `/wishlist`; params?: Router.UnknownInputParams; };
    }
  }
}
